### ISSUE TITLE
Elevated permissions should not be required on windows

### ISSUE THREAD

**Issue by jonnyzzz** [gogradle/gogradle#92] opened 2017-05-05 10:16 UTC
I have the following error 
```
Caused by: com.github.blindpirate.gogradle.core.exceptions.BuildException: Create symbolic link at ...-consul\.gogradle\proj
ect_gopath\src\****\consul-helper failed
        at com.github.blindpirate.gogradle.core.exceptions.BuildException.cannotCreateSymbolicLink(BuildException.java:24)
        at com.github.blindpirate.gogradle.build.DefaultBuildManager.createSymbolicLink(DefaultBuildManager.java:109)
        at com.github.blindpirate.gogradle.build.DefaultBuildManager.createProjectSymbolicLinkIfNotExist(DefaultBuildManager.java:101)
        at com.github.blindpirate.gogradle.build.DefaultBuildManager.prepareSymbolicLinks(DefaultBuildManager.java:89)
        at com.github.blindpirate.gogradle.task.PrepareTask.prepare(PrepareTask.java:44)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java
:141)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:1
34)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:1
23)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:632)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:615)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
        ... 70 more
Caused by: java.nio.file.FileSystemException: E:\Work\****\.gogradle\project_gopath\src\****\consul-helper: A required
privilege is not held by the client.

        at com.github.blindpirate.gogradle.build.DefaultBuildManager.createSymbolicLink(DefaultBuildManager.java:107)
        ... 81 more
```

**Comment by blindpirate** [comment] 2017-05-05 11:17
Thanks for reporting, unfortunately, it's by design. Gogradle need to create a symbolic link in `.gogradle/project_gopath`, so either you run it in admin mode or abandon using it on Windows.

**Comment by blindpirate** [comment] 2017-05-09 14:59
I would close this issue. Please let me know if there's any extra question.

**Closed by blindpirate** 2017-05-09 14:59 UTC

**Comment by blindpirate** [comment] 2017-05-23 06:52
Hi @jonnyzzz , with the latest `0.5.2`, the issue you mentioned is resolved and you can have a try.  Thank you.

**Comment by kunickiaj** [comment] 2018-08-15 18:25
Still run into this issue on 0.10, whether or not I'm using an admin level instance of the shell or not.

Is there any workaround to this issue? Seems like builds simply are not currently possible on Windows.

**Comment by blindpirate** [comment] 2018-08-15 23:35
@kunickiaj Workaround is conforming to Go's workspace convention: https://golang.org/doc/code.html#Workspaces

Then start build with `GOPATH` environment variable.

**Comment by ddimtirov** [comment] 2019-09-07 05:03
Another workaround for windows is to try using junctions if symlinks fail (or possibly add an option). Junctions do not work across filesystems, but have the benefit of not requiring elevated permissions.

On Win7+ you can create junctions by running the following executable:

`cmd.exe /c mklink /j <target> <actual_dir>`

Note that the arguments are swapped (if you compare to `ln`)
